services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    volumes:
      - ~/.kube:/root/.kube:ro
      - ~/.aws:/root/.aws:ro

    environment:
      KUBECONFIG: /root/.kube/config
      AWS_PROFILE: default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend